# Generated by Django 3.1.3 on 2020-11-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='profile_pic',
        ),
    ]
